import Decimal from 'decimal.js';import type {Transaction} from './types';import {D} from './format';
export const deductionFields=['deduction1','deduction2','deduction3','contractDeductions','deduction4','deduction5','lineCharges'] as const;
export function releaseKey(r:Transaction){return r.barcode?`barcode:${r.barcode}`:r.catalogNumber?`cat:${r.catalogNumber}`:r.releaseCode?`code:${r.releaseCode}`:`fallback:${r.artist}|${r.albumTitle}`;}
export function isTrackRow(r:Transaction){if(!r.isrc&&/bundle/i.test(`${r.assetType} ${r.usageType}`))return false;return !!r.isrc||/track/i.test(r.assetType)||/^track\b/i.test(r.usageType);}
export function trackKey(r:Transaction){return r.isrc?`isrc:${r.isrc}`:`fallback:${releaseKey(r)}|${r.artist}|${r.trackTitle}`;}
export function totals(rows:Transaction[]){return rows.reduce((a,r)=>({amount:a.amount.plus(D(r.amount)),royaltyAmount:a.royaltyAmount.plus(D(r.royaltyAmount)),sales:a.sales.plus(D(r.sales)),returns:a.returns.plus(D(r.returns)),deductions:a.deductions.plus(deductionFields.reduce((s,k)=>s.plus(D(r[k])),new Decimal(0))),lineCharges:a.lineCharges.plus(D(r.lineCharges))}),{amount:new Decimal(0),royaltyAmount:new Decimal(0),sales:new Decimal(0),returns:new Decimal(0),deductions:new Decimal(0),lineCharges:new Decimal(0)});}
function group(rows:Transaction[],key:(r:Transaction)=>string, seed:(r:Transaction)=>Record<string,unknown>){const m=new Map<string,any>(); for(const r of rows){const k=key(r)||'(blank)'; if(!m.has(k))m.set(k,{key:k,...seed(r),rows:[],releaseSet:new Set(),trackSet:new Set(),shopSet:new Set(),countrySet:new Set(),artistSet:new Set()}); const g=m.get(k); g.rows.push(r); g.releaseSet.add(releaseKey(r)); if(isTrackRow(r))g.trackSet.add(trackKey(r)); if(r.shop)g.shopSet.add(r.shop); if(r.country)g.countrySet.add(r.country); if(r.artist)g.artistSet.add(r.artist);} return [...m.values()].map(g=>({...g,...totals(g.rows),releaseCount:g.releaseSet.size,trackCount:g.trackSet.size,shopCount:g.shopSet.size,countryCount:g.countrySet.size,artistCount:g.artistSet.size,transactionRows:g.rows.length})).sort((a,b)=>b.royaltyAmount.cmp(a.royaltyAmount));}
export const groupArtists=(r:Transaction[])=>group(r,x=>x.artist,x=>({artist:x.artist}));
export const groupReleases=(r:Transaction[])=>group(r,releaseKey,x=>({albumTitle:x.albumTitle,artist:x.artist,releaseCode:x.releaseCode,catalogNumber:x.catalogNumber,barcode:x.barcode}));
export const groupTracks=(r:Transaction[])=>group(r.filter(isTrackRow),trackKey,x=>({artist:x.artist,trackTitle:x.trackTitle,isrc:x.isrc,albumTitle:x.albumTitle,catalogNumber:x.catalogNumber,barcode:x.barcode}));
export const groupBy=(r:Transaction[],field:keyof Transaction)=>group(r,x=>String(x[field]||'(blank)'),x=>({[field]:x[field]}));
export function rateSummary(rows:Transaction[]){const rates=group(rows.filter(r=>r.royaltyRate),r=>r.royaltyRate,r=>({royaltyRate:r.royaltyRate}));return {label:rates.length===0?'No rate supplied':rates.length===1?`${D(rates[0].royaltyRate).mul(100).toString()}%`:'Multiple rates',rates};}
export function periodSortValue(v:string){const s=String(v); const m=s.match(/^(\d{4})[-_ ]?(\d{2})/); if(m)return `${m[1]}-${m[2]}`; const n=Number(s); if(n>20000&&n<80000)return new Date((n-25569)*86400e3).toISOString().slice(0,10); const d=new Date(s); return isNaN(d.getTime())?s:d.toISOString().slice(0,10);}
export function searchRows(rows:Transaction[],field:keyof Transaction,query:string,exact=false,indexes?:Record<string,Map<string,number[]>>){const q=query.toLowerCase();if(exact&&indexes?.[String(field)]?.has(q))return indexes[String(field)].get(q)!.map(i=>rows[i]).filter(Boolean);return rows.filter(r=>exact?String(r[field]).toLowerCase()===q:String(r[field]).toLowerCase().includes(q));}
