import Decimal from 'decimal.js';import type {Transaction} from './types';import {D} from './format';
export const deductionFields=['deduction1','deduction2','deduction3','contractDeductions','deduction4','deduction5','lineCharges'] as const;
export function releaseKey(r:Transaction){return r.barcode?`barcode:${r.barcode}`:r.catalogNumber?`cat:${r.catalogNumber}`:r.releaseCode?`code:${r.releaseCode}`:`fallback:${r.artist}|${r.albumTitle}`;}
export function isTrackRow(r:Transaction){if(!r.isrc&&/bundle/i.test(`${r.assetType} ${r.usageType}`))return false;return !!r.isrc||/track/i.test(r.assetType)||/^track\b/i.test(r.usageType);}
export function trackKey(r:Transaction){return r.isrc?`isrc:${r.isrc}`:`fallback:${releaseKey(r)}|${r.artist}|${r.trackTitle}`;}
export function totals(rows:Transaction[]){return rows.reduce((a,r)=>({amount:a.amount.plus(D(r.amount)),royaltyAmount:a.royaltyAmount.plus(D(r.royaltyAmount)),sales:a.sales.plus(D(r.sales)),returns:a.returns.plus(D(r.returns)),deductions:a.deductions.plus(deductionFields.reduce((s,k)=>s.plus(D(r[k])),new Decimal(0))),lineCharges:a.lineCharges.plus(D(r.lineCharges))}),{amount:new Decimal(0),royaltyAmount:new Decimal(0),sales:new Decimal(0),returns:new Decimal(0),deductions:new Decimal(0),lineCharges:new Decimal(0)});}
export const unspecifiedLabels:Partial<Record<keyof Transaction,string>>={artist:'Unspecified artist',albumTitle:'Unspecified release',trackTitle:'Unspecified track',shop:'Unspecified shop',country:'Unspecified country',salesPeriod:'Unspecified sales period',usageType:'Unspecified usage type',royaltyRate:'Unspecified royalty rate'};
export function groupValue(r:Transaction,field:keyof Transaction){const v=String(r[field]??'').trim();return v||unspecifiedLabels[field]||`Unspecified ${String(field)}`;}
function group(rows:Transaction[],key:(r:Transaction)=>string, seed:(r:Transaction)=>Record<string,unknown>){const m=new Map<string,any>(); for(const r of rows){const k=key(r).trim()||'(blank)'; if(!m.has(k))m.set(k,{key:k,...seed(r),rows:[],releaseSet:new Set(),trackSet:new Set(),shopSet:new Set(),countrySet:new Set(),artistSet:new Set()}); const g=m.get(k); g.rows.push(r); g.releaseSet.add(releaseKey(r)); if(isTrackRow(r))g.trackSet.add(trackKey(r)); g.shopSet.add(groupValue(r,'shop')); g.countrySet.add(groupValue(r,'country')); g.artistSet.add(groupValue(r,'artist'));} return [...m.values()].map(g=>({...g,...totals(g.rows),releaseCount:g.releaseSet.size,trackCount:g.trackSet.size,shopCount:g.shopSet.size,countryCount:g.countrySet.size,artistCount:g.artistSet.size,transactionRows:g.rows.length})).sort((a,b)=>b.royaltyAmount.cmp(a.royaltyAmount));}
export const groupArtists=(r:Transaction[])=>group(r,x=>groupValue(x,'artist'),x=>({artist:groupValue(x,'artist')}));
export const groupReleases=(r:Transaction[])=>group(r,releaseKey,x=>({albumTitle:x.albumTitle||unspecifiedLabels.albumTitle,artist:groupValue(x,'artist'),releaseCode:x.releaseCode,catalogNumber:x.catalogNumber,barcode:x.barcode}));
export const trackRows=(r:Transaction[])=>r.filter(isTrackRow);
export const groupTracks=(r:Transaction[])=>group(trackRows(r),trackKey,x=>({artist:groupValue(x,'artist'),trackTitle:x.trackTitle||unspecifiedLabels.trackTitle,isrc:x.isrc,albumTitle:x.albumTitle||unspecifiedLabels.albumTitle,catalogNumber:x.catalogNumber,barcode:x.barcode}));
export const groupBy=(r:Transaction[],field:keyof Transaction)=>group(r,x=>groupValue(x,field),x=>({[field]:groupValue(x,field)}));
export function validRateValue(v:unknown){const s=String(v??'').trim(); if(!s)return ''; try{const d=new Decimal(s); return d.isFinite()?d.toString():''}catch{return ''}}
export function groupRoyaltyRates(rows:Transaction[]){return group(rows.filter(r=>validRateValue(r.royaltyRate)),x=>validRateValue(x.royaltyRate),x=>({royaltyRate:validRateValue(x.royaltyRate)}));}
export function rateSummary(rows:Transaction[]){const rates=groupRoyaltyRates(rows);return {label:rates.length===0?'Rate not supplied':rates.length===1?`${D(rates[0].royaltyRate).mul(100).toString()}%`:'Multiple rates',rates};}
export function periodSortValue(v:string){const s=String(v); const m=s.match(/^(\d{4})[-_ ]?(\d{2})/); if(m)return `${m[1]}-${m[2]}`; const n=Number(s); if(n>20000&&n<80000)return new Date((n-25569)*86400e3).toISOString().slice(0,10); const d=new Date(s); return isNaN(d.getTime())?s:d.toISOString().slice(0,10);}
export function searchRows(rows:Transaction[],field:keyof Transaction,query:string,exact=false,indexes?:Record<string,Map<string,number[]>>){const q=query.toLowerCase();if(exact&&indexes?.[String(field)]?.has(q))return indexes[String(field)].get(q)!.map(i=>rows[i]).filter(Boolean);return rows.filter(r=>exact?String(r[field]).toLowerCase()===q:String(r[field]).toLowerCase().includes(q));}

export function groupedReconciliation(rows:Transaction[],groups:any[]){const dashboard=totals(rows);const grouped=groups.reduce((a,g)=>({royaltyAmount:a.royaltyAmount.plus(D(g.royaltyAmount)),amount:a.amount.plus(D(g.amount)),sales:a.sales.plus(D(g.sales)),returns:a.returns.plus(D(g.returns))}),{royaltyAmount:new Decimal(0),amount:new Decimal(0),sales:new Decimal(0),returns:new Decimal(0)});const diff={royaltyAmount:grouped.royaltyAmount.minus(dashboard.royaltyAmount),amount:grouped.amount.minus(dashboard.amount),sales:grouped.sales.minus(dashboard.sales),returns:grouped.returns.minus(dashboard.returns)};const reconciled=diff.royaltyAmount.abs().lte(0.0001)&&diff.amount.abs().lte(0.0001)&&diff.sales.isZero()&&diff.returns.isZero();return{dashboard,grouped,diff,reconciled};}
