import Decimal from 'decimal.js';import type {Transaction} from './types';import {D} from './format';
export const deductionFields=['deduction1','deduction2','deduction3','contractDeductions','deduction4','deduction5','lineCharges'] as const;
export function releaseKey(r:Transaction){const barcode=String(r.barcode??'').trim(),catalogNumber=String(r.catalogNumber??'').trim(),releaseCode=String(r.releaseCode??'').trim(),artist=groupValue(r,'artist'),albumTitle=groupValue(r,'albumTitle');return barcode?`barcode:${barcode}`:catalogNumber?`cat:${catalogNumber}`:releaseCode?`code:${releaseCode}`:`fallback:${artist}|${albumTitle}`;}
export function isTrackRow(r:Transaction){if(!r.isrc&&/bundle/i.test(`${r.assetType} ${r.usageType}`))return false;return !!r.isrc||/track/i.test(r.assetType)||/^track\b/i.test(r.usageType);}
export function trackKey(r:Transaction){return r.isrc?`isrc:${r.isrc}`:`fallback:${releaseKey(r)}|${r.artist}|${r.trackTitle}`;}
export function totals(rows:Transaction[]){return rows.reduce((a,r)=>({amount:a.amount.plus(D(r.amount)),royaltyAmount:a.royaltyAmount.plus(D(r.royaltyAmount)),sales:a.sales.plus(D(r.sales)),returns:a.returns.plus(D(r.returns)),deductions:a.deductions.plus(deductionFields.reduce((s,k)=>s.plus(D(r[k])),new Decimal(0))),lineCharges:a.lineCharges.plus(D(r.lineCharges))}),{amount:new Decimal(0),royaltyAmount:new Decimal(0),sales:new Decimal(0),returns:new Decimal(0),deductions:new Decimal(0),lineCharges:new Decimal(0)});}
export const unspecifiedLabels:Partial<Record<keyof Transaction,string>>={artist:'Unspecified artist',albumTitle:'Unspecified release',trackTitle:'Unspecified track',shop:'Unspecified shop',country:'Unspecified country',salesPeriod:'Unspecified sales period',usageType:'Unspecified usage type',royaltyRate:'Unspecified royalty rate'};
export function groupValue(r:Transaction,field:keyof Transaction){const v=String(r[field]??'').trim();return v||unspecifiedLabels[field]||`Unspecified ${String(field)}`;}
function addTotals(g:any,r:Transaction){g.amount=g.amount.plus(D(r.amount));g.royaltyAmount=g.royaltyAmount.plus(D(r.royaltyAmount));g.sales=g.sales.plus(D(r.sales));g.returns=g.returns.plus(D(r.returns));g.deductions=g.deductions.plus(deductionFields.reduce((s,k)=>s.plus(D(r[k])),new Decimal(0)));g.lineCharges=g.lineCharges.plus(D(r.lineCharges));}
function group(rows:Transaction[],key:(r:Transaction)=>string, seed:(r:Transaction)=>Record<string,unknown>){const m=new Map<string,any>(); for(let rowIndex=0;rowIndex<rows.length;rowIndex++){const r=rows[rowIndex];const k=key(r).trim()||'(blank)'; if(!m.has(k))m.set(k,{key:k,...seed(r),amount:D(0),royaltyAmount:D(0),sales:D(0),returns:D(0),deductions:D(0),lineCharges:D(0),transactionRows:0,releaseSet:new Set(),trackSet:new Set(),shopSet:new Set(),countrySet:new Set(),artistSet:new Set(),catalogNumberSet:new Set<string>(),releaseCodeSet:new Set<string>(),barcodeSet:new Set<string>(),albumTitleSet:new Set<string>()}); const g=m.get(k); g.transactionRows++; addTotals(g,r); g.releaseSet.add(releaseKey(r)); if(isTrackRow(r))g.trackSet.add(trackKey(r)); g.shopSet.add(groupValue(r,'shop')); g.countrySet.add(groupValue(r,'country')); g.artistSet.add(groupValue(r,'artist')); const cat=String(r.catalogNumber??'').trim(),code=String(r.releaseCode??'').trim(),barcode=String(r.barcode??'').trim(),album=String(r.albumTitle??'').trim(),artist=String(r.artist??'').trim(); if(cat)g.catalogNumberSet.add(cat); if(code)g.releaseCodeSet.add(code); if(barcode)g.barcodeSet.add(barcode); if(album)g.albumTitleSet.add(album); if(artist)g.artistSet.add(artist);} return [...m.values()].map(g=>{const {releaseSet,trackSet,shopSet,countrySet,artistSet,catalogNumberSet,releaseCodeSet,barcodeSet,albumTitleSet,...rest}=g;return{...rest,releaseCount:releaseSet.size,trackCount:trackSet.size,shopCount:shopSet.size,countryCount:countrySet.size,artistCount:artistSet.size,catalogNumbers:[...catalogNumberSet].sort(),releaseCodes:[...releaseCodeSet].sort(),barcodes:[...barcodeSet].sort(),albumTitles:[...albumTitleSet].sort(),artists:[...artistSet].sort()}}).sort((a,b)=>b.royaltyAmount.cmp(a.royaltyAmount));}
export const groupArtists=(r:Transaction[])=>group(r,x=>groupValue(x,'artist'),x=>({artist:groupValue(x,'artist')}));

function displayDistinct(values:string[]){return values.length>1?values.join(' | '):values[0]??'';}
export const groupReleases=(r:Transaction[])=>group(r,releaseKey,x=>({albumTitle:groupValue(x,'albumTitle'),artist:groupValue(x,'artist'),releaseCode:String(x.releaseCode??'').trim(),catalogNumber:String(x.catalogNumber??'').trim(),barcode:String(x.barcode??'').trim()})).map(g=>{const catalogNumbers=g.catalogNumbers??[],releaseCodes=g.releaseCodes??[],barcodes=g.barcodes??[],albumTitles=g.albumTitles??[],artists=g.artists??[];return{...g,barcode:displayDistinct(barcodes),albumTitle:albumTitles.length?displayDistinct(albumTitles):unspecifiedLabels.albumTitle,artist:artists.length?displayDistinct(artists):unspecifiedLabels.artist,catalogNumber:displayDistinct(catalogNumbers),releaseCode:displayDistinct(releaseCodes),catalogNumbers,releaseCodes,barcodes,albumTitles,artists,hasMultipleIdentifiers:catalogNumbers.length>1||releaseCodes.length>1||barcodes.length>1||albumTitles.length>1||artists.length>1};});
export const trackRows=(r:Transaction[])=>r.filter(isTrackRow);
export const groupTracks=(r:Transaction[])=>group(trackRows(r),trackKey,x=>({artist:groupValue(x,'artist'),trackTitle:x.trackTitle||unspecifiedLabels.trackTitle,isrc:x.isrc,albumTitle:x.albumTitle||unspecifiedLabels.albumTitle,catalogNumber:x.catalogNumber,barcode:x.barcode}));
export const groupBy=(r:Transaction[],field:keyof Transaction)=>group(r,x=>groupValue(x,field),x=>({[field]:groupValue(x,field)}));
export function validRateValue(v:unknown){const s=String(v??'').trim(); if(!s)return ''; try{const d=new Decimal(s); return d.isFinite()?d.toString():''}catch{return ''}}
export function groupRoyaltyRates(rows:Transaction[]){return group(rows.filter(r=>validRateValue(r.royaltyRate)),x=>validRateValue(x.royaltyRate),x=>({royaltyRate:validRateValue(x.royaltyRate)}));}
export function rateSummary(rows:Transaction[]){const rates=groupRoyaltyRates(rows);return {label:rates.length===0?'Rate not supplied':rates.length===1?`${D(rates[0].royaltyRate).mul(100).toString()}%`:'Multiple rates',rates};}
export function periodSortValue(v:string){const s=String(v); const m=s.match(/^(\d{4})[-_ ]?(\d{2})/); if(m)return `${m[1]}-${m[2]}`; const n=Number(s); if(n>20000&&n<80000)return new Date((n-25569)*86400e3).toISOString().slice(0,10); const d=new Date(s); return isNaN(d.getTime())?s:d.toISOString().slice(0,10);}
export function searchRows(rows:Transaction[],field:keyof Transaction,query:string,exact=false,indexes?:Record<string,Map<string,number[]>>){const q=query.toLowerCase();if(exact&&indexes?.[String(field)]?.has(q))return indexes[String(field)].get(q)!.map(i=>rows[i]).filter(Boolean);return rows.filter(r=>exact?String(r[field]).toLowerCase()===q:String(r[field]).toLowerCase().includes(q));}

export function importCheckGroups(rows:Transaction[]){return {artists:groupArtists(rows),releases:groupReleases(rows),tracks:groupTracks(rows),shops:groupBy(rows,'shop'),countries:groupBy(rows,'country'),salesPeriods:groupBy(rows,'salesPeriod').sort((a,b)=>periodSortValue(a.salesPeriod).localeCompare(periodSortValue(b.salesPeriod))),usageTypes:groupBy(rows,'usageType'),royaltyRates:groupRoyaltyRates(rows)}}
export function groupedReconciliation(rows:Transaction[],groups:any[]){const dashboard=totals(rows);const grouped=groups.reduce((a,g)=>({royaltyAmount:a.royaltyAmount.plus(D(g.royaltyAmount)),amount:a.amount.plus(D(g.amount)),sales:a.sales.plus(D(g.sales)),returns:a.returns.plus(D(g.returns))}),{royaltyAmount:new Decimal(0),amount:new Decimal(0),sales:new Decimal(0),returns:new Decimal(0)});const diff={royaltyAmount:grouped.royaltyAmount.minus(dashboard.royaltyAmount),amount:grouped.amount.minus(dashboard.amount),sales:grouped.sales.minus(dashboard.sales),returns:grouped.returns.minus(dashboard.returns)};const reconciled=diff.royaltyAmount.abs().lte(0.0001)&&diff.amount.abs().lte(0.0001)&&diff.sales.isZero()&&diff.returns.isZero();return{dashboard,grouped,diff,reconciled};}

export type OverviewChartData={topReleases:any[];topArtists:any[];topShops:any[];salesPeriods:any[];usageTypes:any[];filteredRoyaltyTotal:Decimal};
function chartGroup(g:any){const {returns,...rest}=g;void returns;return rest}
function topByRoyalty(groups:any[],limit=10){return groups.filter(g=>!D(g.royaltyAmount).isZero()).sort((a,b)=>D(b.royaltyAmount).cmp(D(a.royaltyAmount))).slice(0,limit).map(chartGroup)}
export function prepareOverviewChartData(groups:{releases:any[];artists:any[];shops:any[];salesPeriods:any[];usageTypes:any[]}):OverviewChartData{const topReleases=topByRoyalty(groups.releases,10);const topArtists=topByRoyalty(groups.artists,10);const topShops=topByRoyalty(groups.shops,10);const salesPeriods=groups.salesPeriods.filter(g=>String(g.salesPeriod??'').trim()&&g.salesPeriod!==unspecifiedLabels.salesPeriod).sort((a,b)=>periodSortValue(a.salesPeriod).localeCompare(periodSortValue(b.salesPeriod))).map(chartGroup);const usageSorted=groups.usageTypes.filter(g=>!D(g.royaltyAmount).isZero()).sort((a,b)=>D(b.royaltyAmount).cmp(D(a.royaltyAmount))).map(chartGroup);const usageTypes=usageSorted.length>10?[...usageSorted.slice(0,10),usageSorted.slice(10).reduce((a,g)=>({usageType:'Other',royaltyAmount:a.royaltyAmount.plus(D(g.royaltyAmount)),amount:a.amount.plus(D(g.amount)),sales:a.sales.plus(D(g.sales)),transactionRows:a.transactionRows+(g.transactionRows??0)}),{usageType:'Other',royaltyAmount:D(0),amount:D(0),sales:D(0),transactionRows:0})]:usageSorted;const filteredRoyaltyTotal=groups.shops.reduce((a,g)=>a.plus(D(g.royaltyAmount)),D(0));return{topReleases,topArtists,topShops,salesPeriods,usageTypes,filteredRoyaltyTotal}}
export function prepareOverviewChartDataFromRows(rows:Transaction[]){return prepareOverviewChartData({releases:groupReleases(rows),artists:groupArtists(rows),shops:groupBy(rows,'shop'),salesPeriods:groupBy(rows,'salesPeriod'),usageTypes:groupBy(rows,'usageType')})}
function encodeRowIdentifier(r:Transaction){const sheet=String(r.sourceSheet??''),row=String(r.sourceRow??'');return `${sheet.length}:${sheet}${row.length}:${row};`}
function bytesToHex(bytes:Uint8Array){return [...bytes].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function sha256Hex(value:string){const subtle=globalThis.crypto?.subtle;if(subtle){const digest=await subtle.digest('SHA-256',new TextEncoder().encode(value));return bytesToHex(new Uint8Array(digest))}let h1=0x811c9dc5,h2=0x01000193,h3=0x9e3779b9,h4=0x85ebca6b;for(let i=0;i<value.length;i++){const c=value.charCodeAt(i);h1=Math.imul(h1^c,0x01000193)>>>0;h2=Math.imul(h2+c,0x85ebca6b)>>>0;h3=Math.imul(h3^(c+h1),0xc2b2ae35)>>>0;h4=Math.imul(h4+(c^h2),0x27d4eb2f)>>>0}return [h1,h2,h3,h4].map(n=>n.toString(16).padStart(8,'0')).join('')}
export async function chartDatasetCacheKey(rows:Transaction[]){const identifiers=rows.map(encodeRowIdentifier).sort();return `chart-v2:${rows.length}:${await sha256Hex(identifiers.join('|'))}`}
export async function overviewChartDataForRows(rows:Transaction[],cache:Record<string,OverviewChartData>={}){const key=await chartDatasetCacheKey(rows);if(cache[key])return{key,data:cache[key],fromCache:true};const data=prepareOverviewChartDataFromRows(rows);cache[key]=data;return{key,data,fromCache:false}}
