import {describe,it,expect} from 'vitest';import * as XLSX from 'xlsx';import {detectHeaderRow,parseWorkbook,normaliseIdentifier,parseRoyaltyRate} from './parser';import {clampProgress,isLargeFile,IMPORT_STAGES} from './importProgress';import {fieldLabels} from './columnAliases';import {toCsv} from './exportCsv';import {D,fmtRate,fmtMoney} from './format';import {sampleStatement} from './sampleData';import {ensureImportTimings,recordTiming,recordTimingValue,safeNow} from './timing';import {groupArtists,groupReleases,groupTracks,groupBy,groupRoyaltyRates,rateSummary,importCheckGroups,periodSortValue,searchRows,totals,groupedReconciliation,isTrackRow} from './analytics';
const headers=Object.values(fieldLabels);const row=['C1','Contract','', 'Track','R1','Release A','CAT-001','1234567890123','ISRC1','Artist A','Track A','Track Stream','GB','Shop A','2026-06','10','1','0.1','1.20','','','','','','','','','','','0.85','1.02'];
function wb(aoa:any[][],name='Digital Sales'){const w=XLSX.utils.book_new();XLSX.utils.book_append_sheet(w,XLSX.utils.aoa_to_sheet(aoa),name);return w}
describe('parsing',()=>{it('detects header row and known Details columns',()=>{const h=detectHeaderRow([['title'],headers]);expect(h?.idx).toBe(1);expect(h?.map.get('royaltyAmount')).toBe(30)});it('handles aliases, blank sheets, reordered columns, numeric/currency strings and csv-like workbooks',()=>{const w=wb([[]],'Blank');XLSX.utils.book_append_sheet(w,XLSX.utils.aoa_to_sheet([['x'],['Artist','Release Title','Track Title','Revenue Amount','Label Earnings','Cat Number','EAN'],['A','R','T','£1,000.10','850.085','00001','1.23457E+12']]),'Other');const s=parseWorkbook(w,'KIKA___2026_06_01___2026_06_30-4.xlsx',123);expect(s.diagnostics.worksheetsIgnored[0]).toContain('blank');expect(s.diagnostics.account).toBe('KIKA');expect(s.rows[0].catalogNumber).toBe('00001');expect(s.rows[0].barcode).toBe('1234570000000');expect(D(s.rows[0].amount).toString()).toBe('1000.1')});it('throws clear missing required error',()=>expect(()=>parseWorkbook(wb([['Artist'],['A']]))).toThrow(/missing/));it('normalises scientific identifiers',()=>expect(normaliseIdentifier('1.23E+5')).toBe('123000'));it('parses royalty rates from decimals, numbers and percentages',()=>{expect(parseRoyaltyRate('100%')?.toString()).toBe('1');expect(parseRoyaltyRate('100.00%')?.toString()).toBe('1');expect(parseRoyaltyRate('85%')?.toString()).toBe('0.85');expect(parseRoyaltyRate('85.0%')?.toString()).toBe('0.85');expect(parseRoyaltyRate(' 1,000.00% ')?.toString()).toBe('10');expect(parseRoyaltyRate(0.85)?.toString()).toBe('0.85');expect(parseRoyaltyRate(1)?.toString()).toBe('1');expect(parseRoyaltyRate(85)?.toString()).toBe('0.85');expect(parseRoyaltyRate('not a rate')).toBeNull()});it('normalises percentage royalty rates and records invalid rates without throwing',()=>{const percent=[...row];percent[29]='100.00%';percent[30]='1.20';const invalid=[...row];invalid[29]='bad%';const s=parseWorkbook(wb([headers,percent,invalid]));expect(s.rows[0].royaltyRate).toBe('1');expect(s.rows[1].royaltyRate).toBe('');expect(s.diagnostics.invalidNumericValues[0]).toContain('Royalty Rate could not be parsed')})});
describe('calculations and grouping',()=>{const s=parseWorkbook(wb([headers,row,[...row.slice(0,7),'1234567890123','ISRC2','Artist A','Track B','Bundle DL','US','Shop B','2026_05','5','0','0.2','2.00','','','','-0.1','','','','','','-0.2','0.80','1.60'],[...row.slice(0,6),'CAT-002','','','Artist B','Bundle','Bundle DL','GB','Shop A','202605','1','0','','3.00','','','','','','','','','','','0.85','2.55']]));it('uses decimal-safe totals',()=>{const t=totals(s.rows);expect(t.amount.toString()).toBe('6.2');expect(t.royaltyAmount.toString()).toBe('5.17');expect(t.sales.toString()).toBe('16');expect(t.returns.toString()).toBe('1');expect(t.deductions.toString()).toBe('-0.3');expect(t.lineCharges.toString()).toBe('-0.2')});it('formats rates',()=>{expect(fmtRate('0.85')).toBe('85%');expect(new Set(s.rows.map(r=>r.royaltyRate)).size).toBe(2)});it('groups artists/releases/tracks/shops/countries and excludes blank bundle ISRC track',()=>{expect(groupArtists(s.rows)[0].artist).toBe('Artist A');expect(groupReleases(s.rows).length).toBe(2);expect(groupTracks(s.rows).length).toBe(2);expect(groupBy(s.rows,'shop').length).toBe(2);expect(groupBy(s.rows,'country').length).toBe(2);expect(['2026-05','2026-06']).toEqual(['2026_05','2026-06'].sort((a,b)=>periodSortValue(a).localeCompare(periodSortValue(b))).map(periodSortValue))});it('searches only the selected source field and supports exact identifiers',()=>{expect(searchRows(s.rows,'artist','Release A').length).toBe(0);expect(searchRows(s.rows,'albumTitle','Release A').length).toBe(3);expect(searchRows(s.rows,'trackTitle','Track A').length).toBe(1);expect(searchRows(s.rows,'catalogNumber','CAT-001',true).length).toBe(2);expect(searchRows(s.rows,'barcode','1234567890123',true).length).toBe(2);expect(searchRows(s.rows,'isrc','ISRC1',true).length).toBe(1)});it('classifies validation and duplicates',()=>{expect(s.diagnostics.royaltyValidation.matches).toBeGreaterThan(0);expect(s.diagnostics.royaltyValidation.notChecked).toBeGreaterThan(0);const dup=parseWorkbook(wb([headers,row,row]));expect(dup.diagnostics.duplicateLookingRows).toBe(2)})});

describe('large import progress helpers',()=>{it('keeps stages ordered and progress monotonic',()=>{let p=0;for(const stage of IMPORT_STAGES){const n=clampProgress(p,stage,1);expect(n).toBeGreaterThanOrEqual(p);p=n}expect(p).toBe(100)});it('enables Large File Mode by size or estimated rows',()=>{expect(isLargeFile(11*1024*1024,1)).toBe(true);expect(isLargeFile(1,50001)).toBe(true);expect(isLargeFile(1,50000)).toBe(false)});it('chunks large rows, defers duplicates and drops raw row copies',()=>{const rows=Array.from({length:5001},(_,i)=>[...row.slice(0,15),String(i+1),'0','0.1','1.00','','','','','','','','','','','0.85','0.85']);const events:any[]=[];const s=parseWorkbook(wb([headers,...rows]),'large.xlsx',11*1024*1024,{onProgress:e=>events.push(e)});expect(s.diagnostics.largeFileMode).toBe(true);expect(events.filter(e=>e.stage==='Importing transactions').length).toBeGreaterThan(1);expect(s.rows[0].originalRow).toBeUndefined();expect(s.diagnostics.duplicateLookingRows).toBe(0);expect(s.diagnostics.initialSummary?.transactionCount).toBe(5001);expect(events.at(-1).percent).toBe(100)});it('row-level problems do not stop full import',()=>{const bad=[...row];bad[29]='bad%';const s=parseWorkbook(wb([headers,bad,row]));expect(s.rows.length).toBe(2);expect(s.diagnostics.invalidNumericValues.length).toBeGreaterThan(0)})});

describe('grouped export reconciliation regressions',()=>{
  const tx=(i:number,over:Partial<any>={})=>({sourceSheet:'s',sourceRow:i,contractId:'',contractName:'',shareContract:'',assetType:'Track',releaseCode:`R${i%5}`,albumTitle:`Release ${i%7}`,catalogNumber:`CAT${i%7}`,barcode:`BC${i%7}`,isrc:`ISRC${i}`,artist:`Artist ${i%23}`,trackTitle:`Track ${i%9}`,usageType:i%2?'Stream':'Download',country:i%3===0?'GB':'US',shop:`Shop ${i%25}`,salesPeriod:`2026-${String((i%4)+1).padStart(2,'0')}`,sales:String(i+1),returns:String(i%2),ppu:'0.0001',amount:(0.10001+i/1000).toString(),share:'',rata1:'',rata2:'',deduction1:'',deduction2:'',deduction3:'',contractDeductions:'',deduction4:'',deduction5:'',lineCharges:'',royaltyRate:'0.85',royaltyAmount:(0.0850085+i/10000).toString(),...over});
  const rows=Array.from({length:55},(_,i)=>tx(i,i===3?{shop:''}:i===4?{artist:'',country:'',salesPeriod:'',usageType:''}:{}));
  function expectRecon(groups:any[], subset=rows){const r=groupedReconciliation(subset,groups);expect(r.reconciled).toBe(true);expect(r.grouped.royaltyAmount.toString()).toBe(r.dashboard.royaltyAmount.toString());expect(r.grouped.amount.toString()).toBe(r.dashboard.amount.toString());expect(r.grouped.sales.toString()).toBe(r.dashboard.sales.toString());expect(r.grouped.returns.toString()).toBe(r.dashboard.returns.toString());}
  it('shop export source contains every shop beyond top 10 and reconciles independently of chart data',()=>{const all=groupBy(rows,'shop');const top10=all.slice(0,10);expect(all.length).toBeGreaterThan(20);expect(top10.length).toBe(10);expect(all.map(g=>g.shop)).toContain('Unspecified shop');expectRecon(all);expect(groupedReconciliation(rows,top10).reconciled).toBe(false)});
  it('all grouped summaries reconcile to dashboard totals including blanks',()=>{for(const groups of [groupArtists(rows),groupReleases(rows),groupTracks(rows),groupBy(rows,'country'),groupBy(rows,'salesPeriod'),groupBy(rows,'usageType'),groupBy(rows,'royaltyRate')])expectRecon(groups);expect(groupArtists(rows).map(g=>g.artist)).toContain('Unspecified artist');expect(groupBy(rows,'country').map(g=>g.country)).toContain('Unspecified country');expect(groupBy(rows,'salesPeriod').map(g=>g.salesPeriod)).toContain('Unspecified sales period');expect(groupBy(rows,'usageType').map(g=>g.usageType)).toContain('Unspecified usage type')});
  it('pagination and visual table limits do not limit complete-summary exports',()=>{const all=groupBy(rows,'shop');const page=all.slice(0,10);expect(page.length).toBeLessThan(all.length);expectRecon(all);expect(groupedReconciliation(rows,page).grouped.royaltyAmount.toString()).not.toBe(totals(rows).royaltyAmount.toString())});
  it('global filters affect dashboard and exports consistently while preserving decimal precision',()=>{const filtered=rows.filter(r=>r.country==='GB');const groups=groupBy(filtered,'shop');expect(filtered.length).toBeGreaterThan(0);expectRecon(groups,filtered);expect(totals(filtered).royaltyAmount.decimalPlaces()).toBeGreaterThan(2)});
  it('CSV grouped totals are numeric strings without currency symbols',()=>{const groups=groupBy(rows,'shop');const csv=toCsv([...groups.map(g=>({shop:g.shop,royaltyAmount:g.royaltyAmount.toString(),amount:g.amount.toString(),sales:g.sales.toString(),returns:g.returns.toString()})),{shop:'TOTAL',royaltyAmount:totals(rows).royaltyAmount.toString(),amount:totals(rows).amount.toString(),sales:totals(rows).sales.toString(),returns:totals(rows).returns.toString()}],['shop','royaltyAmount','amount','sales','returns']);expect(csv).toContain('TOTAL');expect(csv).not.toContain('£');expect(csv).toMatch(/"\d+\.\d+"/)});
});


describe('review correctness regressions',()=>{
  const make=(over:any={})=>({sourceSheet:'s',sourceRow:1,contractId:'',contractName:'',shareContract:'',assetType:'Track',releaseCode:'R',albumTitle:'Release',catalogNumber:'CAT',barcode:'BC',isrc:'ISRC',artist:'Artist',trackTitle:'Track',usageType:'Track Stream',country:'GB',shop:'Shop',salesPeriod:'2026-06',sales:'1',returns:'0',ppu:'',amount:'10',share:'',rata1:'',rata2:'',deduction1:'',deduction2:'',deduction3:'',contractDeductions:'',deduction4:'',deduction5:'',lineCharges:'',royaltyRate:'0.85',royaltyAmount:'8.5',...over});
  it('uses isTrackRow consistently so bundle/release/service rows are excluded from tracks',()=>{const rows=[make({isrc:'ISRC1'}),make({isrc:'',assetType:'Track',usageType:'Track Download',trackTitle:'Blank ISRC Track'}),make({isrc:'',assetType:'Bundle',usageType:'Bundle DL',trackTitle:'Bundle Asset'}),make({isrc:'',assetType:'Album',usageType:'Bundle DL',trackTitle:'Bundle DL'}),make({isrc:'',assetType:'Release',usageType:'Service Fee',trackTitle:'Fee'})];const tracks=groupTracks(rows);expect(rows.filter(isTrackRow).length).toBe(2);expect(tracks.length).toBe(2);expect(tracks.map(t=>t.trackTitle)).not.toContain('Bundle Asset');expect(tracks.map(t=>t.trackTitle)).not.toContain('Fee');expect(parseWorkbook(wb([headers,...rows.map(r=>[r.contractId,r.contractName,r.shareContract,r.assetType,r.releaseCode,r.albumTitle,r.catalogNumber,r.barcode,r.isrc,r.artist,r.trackTitle,r.usageType,r.country,r.shop,r.salesPeriod,r.sales,r.returns,r.ppu,r.amount,r.share,r.rata1,r.rata2,r.deduction1,r.deduction2,r.deduction3,r.contractDeductions,r.deduction4,r.deduction5,r.lineCharges,r.royaltyRate,r.royaltyAmount])])).diagnostics.initialSummary?.uniqueTrackCount).toBe(tracks.length);const csv=toCsv(tracks.map(t=>({trackTitle:t.trackTitle,isrc:t.isrc,royaltyAmount:t.royaltyAmount.toString()})),['trackTitle','isrc','royaltyAmount']);expect(csv).not.toContain('Bundle');});
  it('ignores blank and invalid royalty rates for labels and grouped breakdowns',()=>{expect(rateSummary([make({royaltyRate:'0.85'}),make({royaltyRate:''}),make({royaltyRate:''})]).label).toBe('85%');expect(rateSummary([make({royaltyRate:'0.85'}),make({royaltyRate:'0.85'}),make({royaltyRate:'bad'})]).label).toBe('85%');expect(rateSummary([make({royaltyRate:'0.85'}),make({royaltyRate:'1'}),make({royaltyRate:''})]).label).toBe('Multiple rates');expect(rateSummary([make({royaltyRate:''}),make({royaltyRate:''})]).label).toBe('Rate not supplied');expect(groupRoyaltyRates([make({royaltyRate:''})]).length).toBe(0);});
  it('formats visible money as GBP while CSV values remain numeric',()=>{expect(fmtMoney('11416.23')).toBe('£11,416.23');expect(fmtMoney('-125.4')).toBe('-£125.40');expect(fmtMoney(0)).toBe('£0.00');const csv=toCsv([{amount:D('11416.23').toString()}],['amount']);expect(csv).toContain('11416.23');expect(csv).not.toContain('£');});
});


describe('lazy import check and timing regressions',()=>{
  const tx=(i:number,over:any={})=>({sourceSheet:'s',sourceRow:i,contractId:'',contractName:'',shareContract:'',assetType:'Track',releaseCode:`R${i%2}`,albumTitle:`Release ${i%3}`,catalogNumber:`CAT${i%3}`,barcode:`BC${i%3}`,isrc:`ISRC${i}`,artist:`Artist ${i%4}`,trackTitle:`Track ${i}`,usageType:i%2?'Track Stream':'Track DL',country:i%2?'GB':'US',shop:`Shop ${i%5}`,salesPeriod:`2026-0${(i%3)+1}`,sales:String(i+1),returns:String(i%2),ppu:'',amount:(i+1).toString(),share:'',rata1:'',rata2:'',deduction1:'',deduction2:'',deduction3:'',contractDeductions:'',deduction4:'',deduction5:'',lineCharges:'',royaltyRate:i%2?'0.85':'',royaltyAmount:((i+1)*0.85).toString(),...over});
  const rows=Array.from({length:12},(_,i)=>tx(i));
  it('calculates every Import Checks group without visiting lazy tabs first',()=>{const groups=importCheckGroups(rows);expect(groups.shops.length).toBeGreaterThan(0);expect(groups.countries.length).toBeGreaterThan(0);expect(groups.salesPeriods.length).toBeGreaterThan(0);expect(groups.usageTypes.length).toBeGreaterThan(0);expect(groups.royaltyRates.length).toBe(1);expect(groupedReconciliation(rows,groups.shops).reconciled).toBe(true);expect(groupedReconciliation(rows,groups.countries).reconciled).toBe(true);expect(groupedReconciliation(rows,groups.salesPeriods).reconciled).toBe(true);expect(groupedReconciliation(rows,groups.usageTypes).reconciled).toBe(true);expect(groupedReconciliation(rows,[]).reconciled).toBe(false);expect(importCheckGroups(rows)).toEqual(groups);});
  it('creates optional timing diagnostics safely for sample, missing, partial, and unavailable performance cases',()=>{const sample=sampleStatement();expect(sample.diagnostics.importTimings).toBeUndefined();recordTiming(sample.diagnostics,'tabFirstCalculationMs','Shops',1);recordTiming(sample.diagnostics,'tabFirstCalculationMs','Countries',2);recordTiming(sample.diagnostics,'tabFirstCalculationMs','Sales Periods',3);recordTiming(sample.diagnostics,'tabFirstCalculationMs','Import Checks',4);recordTimingValue(sample.diagnostics,'dashboardFirstRenderMs',5);expect(sample.diagnostics.importTimings?.tabFirstCalculationMs?.Shops).toBe(1);expect(sample.diagnostics.importTimings?.tabFirstCalculationMs?.Countries).toBe(2);expect(sample.diagnostics.importTimings?.tabFirstCalculationMs?.['Sales Periods']).toBe(3);expect(sample.diagnostics.importTimings?.tabFirstCalculationMs?.['Import Checks']).toBe(4);expect(sample.diagnostics.importTimings?.dashboardFirstRenderMs).toBe(5);const partial:any={importTimings:{searchIndexMs:{artist:10}}};expect(()=>recordTiming(partial,'searchIndexMs','shop',6)).not.toThrow();expect(partial.importTimings.searchIndexMs.shop).toBe(6);expect(()=>ensureImportTimings(null)).not.toThrow();const original=(globalThis as any).performance;(globalThis as any).performance={now(){throw new Error('timer unavailable')}};expect(()=>safeNow()).not.toThrow();(globalThis as any).performance=original;});
});

describe('workbook opening regression coverage',()=>{
  it('opens a generated workbook from a non-empty ArrayBuffer',async()=>{const bytes=XLSX.write(wb([headers,row]),{type:'array',bookType:'xlsx'});const {parseArrayBuffer}=await import('./parser');const data=await parseArrayBuffer(bytes,'open.xlsx',bytes.byteLength);expect(data.rows.length).toBe(1);expect(data.diagnostics.importTimings?.workbookOpeningMs).toBeGreaterThanOrEqual(0)});
  it('preserves worker errors and serialises non-Error values with non-blank technical details',async()=>{const {serialiseThrown,technicalDetails}=await import('./importDiagnostics');const thrown={code:'BOOM',nested:{why:'test'}};const s=serialiseThrown(thrown);expect(s.message).toContain('BOOM');const details=technicalDetails({processingStage:'Opening workbook',workerEvent:'error',workbookFilename:'bad.xlsx',fileSize:123,arrayBufferSizeBeforeTransfer:123,arrayBufferSizeInsideWorker:123,sheetJsReadAttempt:'conservative',retryAttemptNumber:2},thrown);for(const label of ['error name','error message','stack trace','processing stage','worker event','workbook filename','file size','ArrayBuffer size before transfer','ArrayBuffer size inside the worker','SheetJS read attempt','retry attempt number'])expect(details).toContain(label);expect(details.trim().length).toBeGreaterThan(0)});
  it('rejects empty ArrayBuffers before SheetJS read',async()=>{const {parseArrayBuffer}=await import('./parser');await expect(parseArrayBuffer(new ArrayBuffer(0),'empty.xlsx',0)).rejects.toThrow(/empty/)});
  it('supports conservative retry options after a failed first opening attempt',async()=>{const parser=await import('./parser');const bytes=XLSX.write(wb([headers,row]),{type:'array',bookType:'xlsx'});await expect(parser.parseArrayBuffer(bytes.slice(0),'retry.xlsx',bytes.byteLength,{readOptions:parser.CONSERVATIVE_SHEETJS_READ_OPTIONS,sheetJsReadAttempt:'conservative',retryAttemptNumber:2})).resolves.toMatchObject({rows:[expect.objectContaining({artist:'Artist A'})]})});
});
