import Decimal from 'decimal.js';
import * as XLSX from 'xlsx';
import { columnAliases, fieldLabels, requiredFields, resolveHeader, type FieldKey } from './columnAliases';
import { D, text } from './format';
import type { ImportDiagnostics, StatementData, Transaction } from './types';
const textFields = new Set<FieldKey>(['contractId','releaseCode','catalogNumber','barcode','isrc','country']);
export function parseFilename(filename:string){const m=filename.match(/^([^_]+)___(\d{4})_(\d{2})_(\d{2})___(\d{4})_(\d{2})_(\d{2})/); if(!m)return{}; const f=(y:string,mo:string,d:string)=>new Date(Date.UTC(+y,+mo-1,+d)).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}); return {account:m[1],reportingPeriod:`${f(m[2],m[3],m[4])} to ${f(m[5],m[6],m[7])}`};}
export function normaliseIdentifier(v:unknown){const s=text(v); if(/^\d+(\.\d+)?e\+?\d+$/i.test(s)){return Number(s).toLocaleString('fullwide',{useGrouping:false});} return s;}
export function parseRoyaltyRate(value:unknown){if(value===null||value===undefined)return null; const raw=typeof value==='string'?value.trim():value; if(raw==='')return null; const stringValue=String(raw).trim(); const isPercentage=stringValue.includes('%'); const cleaned=stringValue.replace(/,/g,'').replace(/%/g,'').trim(); if(!cleaned)return null; try{const rate=new Decimal(cleaned); if(!rate.isFinite())return null; return isPercentage||rate.abs().gt(1)?rate.div(100):rate;}catch{return null;}}
function isBlankRow(row:unknown[]){return row.every(c=>text(c)==='');}
export function detectHeaderRow(rows:unknown[][]){let best={idx:-1,count:0,map:new Map<FieldKey,number>()}; for(let i=0;i<Math.min(30,rows.length);i++){const map=new Map<FieldKey,number>(); rows[i].forEach((h,j)=>{const k=resolveHeader(text(h)); if(k&&!map.has(k))map.set(k,j);}); const req=requiredFields.filter(f=>map.has(f)).length; const score=map.size+req*3; if(score>best.count) best={idx:i,count:score,map};} return requiredFields.every(f=>best.map.has(f))?best:null;}
function transaction(row:unknown[], map:Map<FieldKey,number>, sheet:string, sourceRow:number, diag:ImportDiagnostics):Transaction{const get=(k:FieldKey)=>{const v=row[map.get(k)??-1]; if(k==='royaltyRate'){const parsed=parseRoyaltyRate(v); if(parsed===null&&text(v)!=='')diag.invalidNumericValues.push(`${sheet} row ${sourceRow}: Royalty Rate could not be parsed (${text(v)})`); return parsed?.toString()??'';} return textFields.has(k)?normaliseIdentifier(v):text(v);}; return {sourceSheet:sheet,sourceRow,contractId:get('contractId'),contractName:get('contractName'),shareContract:get('shareContract'),assetType:get('assetType'),releaseCode:get('releaseCode'),albumTitle:get('albumTitle'),catalogNumber:get('catalogNumber'),barcode:get('barcode'),isrc:get('isrc'),artist:get('artist'),trackTitle:get('trackTitle'),usageType:get('usageType'),country:get('country'),shop:get('shop'),salesPeriod:get('salesPeriod'),sales:get('sales'),returns:get('returns'),ppu:get('ppu'),amount:get('amount'),share:get('share'),rata1:get('rata1'),rata2:get('rata2'),deduction1:get('deduction1'),deduction2:get('deduction2'),deduction3:get('deduction3'),contractDeductions:get('contractDeductions'),deduction4:get('deduction4'),deduction5:get('deduction5'),lineCharges:get('lineCharges'),royaltyRate:get('royaltyRate'),royaltyAmount:get('royaltyAmount'),originalRow:Object.fromEntries(row.map((v,i)=>[String(i),v]))};}
export function parseWorkbook(wb:XLSX.WorkBook, filename='statement', fileSize=0):StatementData{const rows:Transaction[]=[]; const diag:ImportDiagnostics={filename,fileSize,...parseFilename(filename),worksheetsDetected:wb.SheetNames,worksheetsImported:[],worksheetsIgnored:[],headerRows:{},transactionRows:0,blankRowsIgnored:0,detectedColumns:[],missingOptionalColumns:[],missingRequiredColumns:[],invalidNumericValues:[],unclassifiedDateValues:[],blankArtistValues:0,blankReleaseValues:0,blankIsrcValues:0,bundleRowsWithBlankIsrc:0,duplicateLookingRows:0,royaltyValidation:{matches:0,requiresReview:0,notChecked:0}}; const names=[...wb.SheetNames].sort((a,b)=>(a==='Digital Sales'?-1:b==='Digital Sales'?1:0)); for(const name of names){try{const aoa=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:'',raw:false}) as unknown[][]; if(!aoa.length||aoa.every(isBlankRow)){diag.worksheetsIgnored.push(`${name} (blank)`); continue;} const h=detectHeaderRow(aoa); if(!h){diag.worksheetsIgnored.push(`${name} (no Details table)`); continue;} diag.worksheetsImported.push(name); diag.headerRows[name]=h.idx+1; diag.detectedColumns=[...new Set([...diag.detectedColumns,...[...h.map.keys()].map(k=>fieldLabels[k])])]; for(let r=h.idx+1;r<aoa.length;r++){try{if(isBlankRow(aoa[r])){diag.blankRowsIgnored++; continue;} rows.push(transaction(aoa[r],h.map,name,r+1,diag));}catch(e){diag.invalidNumericValues.push(`${name} row ${r+1}: ${e instanceof Error?e.message:String(e)}`);}}}catch(e){diag.worksheetsIgnored.push(`${name} (parse error)`); diag.invalidNumericValues.push(`${name}: ${e instanceof Error?e.message:String(e)}`);}}
 diag.transactionRows=rows.length; diag.missingRequiredColumns=requiredFields.filter(f=>!diag.detectedColumns.includes(fieldLabels[f])).map(f=>fieldLabels[f]); diag.missingOptionalColumns=(Object.keys(columnAliases) as FieldKey[]).filter(f=>!requiredFields.includes(f)&&!diag.detectedColumns.includes(fieldLabels[f])).map(f=>fieldLabels[f]); if(diag.missingRequiredColumns.length) throw new Error(`The statement is missing the following required columns: ${diag.missingRequiredColumns.join(', ')}`); enrichDiagnostics(rows,diag); return {label:'Uploaded statement',filename,fileSize,rows,diagnostics:diag};}
export async function parseFile(file:File){const buf=await file.arrayBuffer(); const wb=XLSX.read(buf,{type:'array',cellDates:false}); return parseWorkbook(wb,file.name,file.size);}
export function enrichDiagnostics(rows:Transaction[],d:ImportDiagnostics){const seen=new Map<string,number>(); for(const r of rows){try{if(!r.artist)d.blankArtistValues++; if(!r.albumTitle&&!r.catalogNumber&&!r.barcode&&!r.releaseCode)d.blankReleaseValues++; if(!r.isrc)d.blankIsrcValues++; if(!r.isrc&&/bundle/i.test(`${r.assetType} ${r.usageType}`))d.bundleRowsWithBlankIsrc++; const key=[r.artist,r.albumTitle,r.trackTitle,r.isrc,r.shop,r.country,r.salesPeriod,r.usageType,r.sales,r.amount,r.royaltyAmount].join('|'); seen.set(key,(seen.get(key)??0)+1); const adjusted=['share','rata1','rata2','deduction1','deduction2','deduction3','contractDeductions','deduction4','deduction5','lineCharges'].some(k=>!D((r as any)[k]).isZero()); if(adjusted||!r.royaltyRate){d.royaltyValidation.notChecked++;} else if(D(r.amount).mul(D(r.royaltyRate)).minus(D(r.royaltyAmount)).abs().lte(0.0001)) d.royaltyValidation.matches++; else d.royaltyValidation.requiresReview++;}catch(e){d.invalidNumericValues.push(`${r.sourceSheet} row ${r.sourceRow}: ${e instanceof Error?e.message:String(e)}`); d.royaltyValidation.notChecked++;}} d.duplicateLookingRows=[...seen.values()].filter(v=>v>1).reduce((a,v)=>a+v,0);}
